objects/copado__User_Story__c.object
<CustomObject>
    <description>Agile form of requirements gathering</description>
    <fields>
        <fullName>copado__Environment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Current environment of the User Story. This value is added automatically by Copado based on the selected Credential.</description>
        <inlineHelpText>Current environment of the User Story. This value is added automatically by Copado based on the selected Credential.</inlineHelpText>
        <label>Environment</label>
        <referenceTo>copado__Environment__c</referenceTo>
        <relationshipLabel>User Stories</relationshipLabel>
        <relationshipName>User_Stories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>copado__Org_Credential__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Credential used to add or commit metadata and to promote and deploy the User Story to the next Environment.</description>
        <inlineHelpText>Credential used to add or commit metadata and to promote and deploy the User Story to the next Environment.</inlineHelpText>
        <label>Credential</label>
        <referenceTo>copado__Org__c</referenceTo>
        <relationshipLabel>User Stories (Credential)</relationshipLabel>
        <relationshipName>User_Stories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>copado__Promote_and_Deploy__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>When this checkbox is checked, a promotion and deployment of this User Story will be started.</inlineHelpText>
        <label>Promote and Deploy</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>copado__Status__c</fullName>
        <description>Current status of the implementation of the User Story.</description>
        <inlineHelpText>Current status of the implementation of the User Story.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Backlog</fullName>
                </value>
                <value>
                    <fullName>Backburner</fullName>
                </value>
                <value>
                    <fullName>Awaiting Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Ready for testing</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>QA Approved</fullName>
                </value>
                <value>
                    <fullName>UAT Approved</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>User Story</label>
    <nameField>
        <displayFormat>US-{0000000}</displayFormat>
        <label>User Story Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Stories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/UserStoryHandler.cls
public class UserStoryHandler {
    public static void storyStatus(List<copado__User_Story__c> usrData){
        List<copado__User_Story__c> storyData = [SELECT Id, copado__Status__c, copado__Promote_and_Deploy__c,
                   								 copado__Org_Credential__c, copado__Environment__c FROM 
                                                 copado__User_Story__c WHERE Id IN :usrData];
        copado__Environment__c envDev1 = [SELECT Id, Name FROM copado__Environment__c WHERE Name = 'Dev1'];
        System.debug(envDev1.Id);
        for(copado__User_Story__c us : storyData){
            if(us.copado__Environment__c == envDev1.Id && us.copado__Status__c == 'QA Approved'){
                us.copado__Promote_and_Deploy__c = true;
            }
        }
    }
    
   /* public static void storyTask(List<copado__User_Story__c> usrData){
        List<copado__User_Story__c> storyData = [SELECT Id, copado__Status__c, copado__Promote_and_Deploy__c,
                                                 copado__Org_Credential__r.Name, (SELECT Id, Environment__c FROM Tasks) 
                                                 FROM copado__User_Story__c WHERE Id IN :usrData];
        for (copado__User_Story__c us : storyData) {
            if (us.copado__Org_Credential__r.Name != NULL) {
                for (Task t : us.Tasks) {
                    t.Environment__c = us.copado__Org_Credential__r.Name;
                }
            }
        }
    }  */
}